{
 "title": "xiaomi-miio-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_name",
    "label": "设备名称",
    "query": {
     "query": "label_values(xiaomi_cuco_plug_v3_switch_up,device_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "开关状态",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xiaomi_cuco_plug_v3_switch_up{device_name=~\"$device_name\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "插座故障",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xiaomi_cuco_plug_v3_switch_fault{device_name=~\"$device_name\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "当前功率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "xiaomi_cuco_plug_v3_electric_power{device_name=~\"$device_name\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "设备最大功率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "xiaomi_cuco_plug_v3_max_power_limit{device_name=~\"$device_name\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "最大限制功率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "xiaomi_cuco_plug_v3_power_limit_extension{device_name=~\"$device_name\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  }
 ]
}